language: java
jdk:
  - oraclejdk8

sudo: false # faster builds

before_script:
  - chmod +x gradlew
#script:
#  - ./gradlew check
#  - ./gradlew codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
